services:
  Router:
    class: 'Router'
    public: true

  Beauty\Request:
    class: 'Beauty\Request'
    factory: 'Beauty\Request::instance'

  FlashLogger\ProjectList:
    class: 'FlashLogger\ProjectList'
    factory: 'FlashLogger\ProjectListFactory::make'
    arguments:
      - '%flash-logger.projects%'

  ### FlashLogger
  Clients\FlashLogger\Transport:
    class: 'Clients\FlashLogger\Transport'
    arguments:
      $host: '%service.logger.host%'
      $headers: '%service.logger.headers%'
      $options: '%service.logger.options%'

  Clients\FlashLogger\Client:
    class: 'Clients\FlashLogger\Client'
    public: true
    arguments:
      $transport: '@Clients\FlashLogger\Transport'
